baseURL = "https://eduuh.codes"
title = "Edwin Kamau muraya"
theme = "zzo"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

summaryLength = 70
buildFuture = true
publishDir = "hugo-site"
copyright = "&copy;{year}, All Rights Reserved"
timeout = 10000
enableEmoji = true
paginate = 13
rssLimit = 100
enableGitInfo = true
googleAnalytics = "UA-171434852-1"

[markup]

[markup.goldmark]

[markup.goldmark.renderer]
hardWraps = true
unsafe = true
xHTML = true

[markup.highlight]
codeFences = true
lineNos = false
lineNumbersInTable = false
noClasses = false

[markup.tableOfContents]
endLevel = 6
ordered = false
startLevel = 5

[outputs]
home = ["HTML", "RSS", "SearchIndex"]
section = ["HTML", "RSS", "SearchIndex"]
taxonomyTerm = ["HTML", "RSS", "SearchIndex"]
taxonomy = ["HTML", "RSS", "SearchIndex"]

[outputFormats]

[outputFormats.SearchIndex]
mediaType = "application/json"
baseName = "index"
isPlainText = true
notAlternative = true

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

