[[main]]
identifier = "posts"
name = "Posts"
url = "posts"
weight = 1

[[main]]
identifier = "workshop"
name = "workshops"
url = "workshops"
weight = 2

#[[main]]
#parent = "workshop"
#name = "Presentation"
#url = "presentation"


[[main]]
identifier = "showcase"
name = "Showcase"
url = "showcase"
weight = 3

[[main]]
identifier = "archive"
name = "Archive"
url = "archive"
weight = 4

#[[main]]
#identifier = "about"
#name = "About"
#url = "about"
#weight = 5

#[[main]]
#identifier = "gallery"
#name = "Gallery"
#url = "gallery"
#weight = 5

#[[main]]
#parent = "gallery"
#name = "Hackassembly"
#url = "gallery/hackassembly"

#[[main]]
#parent = "gallery"
#name = "Random"
#url = "gallery/random"

