logoText = "edd's Journal"
logoType = "short" # long, short


logo = false # true or ffalse

description = "Edds Journal where i write all my notes in one place!"

viewportSize = "normal"

useFaviconGenerator = true # https://www.favicon-generator.org/
meta_image = ""
enablePinnedPosts=true

hideSingleContentsWhenJSDisabled = false
hideHomeHeaderWhenMobile = false
showMobileMenuTerms = ["tags", "categories", "series"]


themeOptions = ["light","solarized"] # "hacker", "solarized", "kimbie"]


notAllowedTypesInHome = [
  "contact",
  "talks",
  "about/",
  "gallery",
  "gallery/random",
  "gallery/hackassembly",
  "showcase",
  "publication",
  "presentation",
  "resume",
  "about",
]
notAllowedTypesInHomeSidebar = [
  "about",
  "archive",
  "showcase",
  "publication",
  "presentation",
  "resume"
]
notAllowedTypesInArchive = [
  "about",
  "talks",
  "showcase",
  "publication",
  "presentation",
  "resume"
]
notAllowedTypesInHomeFeed = [
  "about",
  "archive",
  "contact",
  "talks",
  "showcase",
  "publication",
  "presentation",
  "resume",
  "gallery"
]

enableUiAnimation = true
# header
homeHeaderType = "text" # text, img, slide
# body
enableBreadcrumb = false
enablePhotoSwipe = true
enableSearch = true
enableSearchHighlight = true
enableGoToTop = true
enableWhoami = false 
summaryShape = "classic" # card, classic, compact
searchResultPosition = "main" # side, main
archiveGroupByDate = "2006" # "2006-01": group by month, "2006": group by year
archivePaginate = 13
paginateWindow = 1
talksPaginate = 5
talksGroupByDate = "2006"
pubPaginate = 20
# whoami

myname = "@eduuh"
email = "edwinkamaumuraya0@outlook.com"
whoami = "Microsoft Student Ambassador (Alpha Milestone). Sofware Engineer and Gegis Student in Making"
bioImageUrl = "/images/edd2.jpg" 
useGravatar = false
location = "Nyeri , Kenya"
organization = "Student at Dedan Kimathi University"
link = "https://github.com/eduuh"
# sidebar

enableBio = true
enableBioImage = true
enableSidebar = true
enableSidebarTags = true
enableSidebarSeries = true
enableSidebarCategories = true
enableHomeSidebarTitles = true
enableListSidebarTitles = true
enableToc = false
hideToc = false
tocFolding = true
tocPosition = "inner" # inner, outer
enableTocSwitch = true
itemsPerCategory = 5
sidebarPosition = "right"

tocLevels = ["h2", "h3", "h4"]
enableSidebarPostsByOrder = false

showFeedLinks = true
showSocialLinks = true
enableLangChange = false

enableThemeChange = true


# comment
enableComment = true
disqus_shortname = "" 

[utterances]       # https://utteranc.es/
  owner = "31909722"              # Your GitHub ID
  repo = "https://github.com/eduuh/mysite"               # The repo to store comments

[gitalk]     # Gitalk is a comment system based on GitHub issues. see https://github.com/gitalk/gitalk
  owner = "eduuh"              # Your GitHub ID
  repo = "mysite"               # The repo to store comments
  clientId = "bc04b79b04cde6c07745"           # Your client ID
  clientSecret = "df03b0070096fb8d0de071828468546b090cd9d3"       # Your client secret



googleTagManager = "" # GTM-XXXXXX
# rss
updatePeriod = "weekly" # Possible values: 'hourly', 'daily', 'weekly', 'monthly', or 'yearly'.
updateFrequency = ""
fullContents = false

# comment
enableComment = true
disqus_shortname = ""
commento = false


[changyan]
changyanAppid = "" # Changyan app id             # 畅言
changyanAppkey = "" # Changyan app key

[livere]
livereUID = "" # LiveRe UID                  # 来必力

# Isso: https://posativ.org/isso/
[isso]
enable = false
scriptSrc = "" # "https://isso.example.com/js/embed.min.js"
dataAttrs = "" # "data-isso='https://isso.example.com' data-isso-require-author='true'"

[socialOptions]
email = "mailto:edwinkamaumuraya0@gmail.com"
phone = ""
twitter = "https://twitter.com/eduuhmuraya"
github = "https://github.com/eduuh"
stack-overflow = "https://stackoverflow.com/users/7425067/ed%c3%bbuh-m%c3%bbraya"
linkedin = "https://www.linkedin.com/in/eduuh/"
youtube = ""
whatsapp = ""

[donationOptions]
enable = false
alipay = ""
wechat = ""
paypal = ""
patreon = ""

# possible share name: ["facebook","twitter", "reddit", "linkedin", "tumblr", "weibo", "douban", "line"]
[[share]]
name = "twitter"
username = "eduuhmuraya"

[[share]]
name = "linkedin"
username = "eduuh"

[[share]]
name = "redit"
username = "eduuhMash"


[[footerLinks]]
name = ""
link = ""

[[footerLinks]]
name = ""
link = ""

# comment
enableComment = true
disqus_shortname = "disqus_2w6YejGiwX"

[[footerLinks]]
  name = "edwin"
  link = "#"
[[footerLinks]]
  name = ""
  link = ""
