version: "2.4"

services:
  blog:
    image: peaceiris/hugo:v0.71.0-mod
    ports:
      - 1313:1313
    volumes:
      - ${PWD}:/src
    command:
      - server
      - --bind=0.0.0.0
      - --buildDrafts
